#cloud-config
ssh_pwauth: no

users:
  - name: yc-practitioner
    gecos: Yandex Cloud Practitioner
    groups: sudo
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    # change hardcoding pub key
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMSkiqSEUWwAsrsufrU90CpMoQZ0q2G1zmPBPbScGsE
